# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: pii_detection.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto
import grpclib


@dataclass
class PIIDetectionRequest(betterproto.Message):
    """Request message containing the text content to analyze"""

    # The text content to analyze for PII
    content: str = betterproto.string_field(1)
    # Optional confidence threshold (0.0-1.0) If not provided, a default value
    # will be used
    threshold: float = betterproto.float_field(2)


@dataclass
class PIIDetectionResponse(betterproto.Message):
    """Response message containing the PII detection results"""

    # List of detected PII entities
    entities: List["PIIEntity"] = betterproto.message_field(1)
    # Summary of detected PII types and counts
    summary: Dict[str, int] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_INT32
    )
    # Optional masked version of the input text with PII replaced
    masked_content: str = betterproto.string_field(3)


@dataclass
class PIIEntity(betterproto.Message):
    """Represents a single detected PII entity"""

    # The detected text
    text: str = betterproto.string_field(1)
    # The type of PII (e.g., EMAIL, PHONE, etc.)
    type: str = betterproto.string_field(2)
    # Human-readable label for the PII type (localized)
    type_label: str = betterproto.string_field(3)
    # Start position in the original text
    start: int = betterproto.int32_field(4)
    # End position in the original text
    end: int = betterproto.int32_field(5)
    # Confidence score (0.0-1.0)
    score: float = betterproto.float_field(6)


class PIIDetectionServiceStub(betterproto.ServiceStub):
    """
    Service for detecting Personally Identifiable Information (PII) in text
    content
    """

    async def detect_p_i_i(
        self, *, content: str = "", threshold: float = 0
    ) -> PIIDetectionResponse:
        """Analyzes text content for PII and returns detailed results"""

        request = PIIDetectionRequest()
        request.content = content
        request.threshold = threshold

        return await self._unary_unary(
            "/pii_detection.PIIDetectionService/DetectPII",
            request,
            PIIDetectionResponse,
        )
